name: task_management_app
description: "Entry test project ITBee."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_gen: 5.2.0
  get: ^4.6.6
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: 2.4.6
  flutter_gen_runner: 5.2.0

flutter_gen:
  output: lib/generated
  line_length: 150
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets
      package_parameter_enabled: false
    enabled: true
  fonts:
    outputs:
      class_name: AppFonts
    enabled: true



flutter:
 
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
